title: Anything-as-Code
description: ""
show_downloads: true
github:
  zip_url: https://github.com/anythingascode/terraform-stack-generator/archive/refs/tags/v0.0.1.zip
google_analytics:
theme: jekyll-theme-architect